# Generated by Django 6.0.3 on 2026-03-28 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_favorite_transport'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='image_credit_link',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='destination',
            name='image_credit_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='hotel',
            name='image_credit_link',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='hotel',
            name='image_credit_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
